[project]
name = "gptdb-serve"
version = "0.7.4"
description = "Add your description here"
authors = [
    { name = "Md Sulaiman", email = "dev.sulaiman@icloud.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">= 3.10"

dependencies = [
    "gptdb-ext",
]

[project.urls]
Homepage = "https://github.com/khulnasoft/GPT-DB"
Documentation = "http://docs.gptdb.cn/docs/overview"
Repository = "https://github.com/khulnasoft/GPT-DB.git"
Issues = "https://github.com/khulnasoft/GPT-DB/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
managed = true
dev-dependencies = []

[project.optional-dependencies]
libro = ["libro>=0.1.25"]
gptdbs = ["poetry"]

[tool.hatch.build.targets.wheel]
packages = ["src/gptdb_serve"]
exclude = [
    "src/gptdb_serve/**/tests",
    "src/gptdb_serve/**/tests/*",
    "src/gptdb_serve/tests",
    "src/gptdb_serve/tests/*",
    "src/gptdb_serve/**/examples",
    "src/gptdb_serve/**/examples/*"
]
