[project]
name = "gptdb-client"
version = "0.7.4"
description = "Add your description here"
authors = [
    { name = "Md Sulaiman", email = "dev.sulaiman@icloud.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">= 3.10"

dependencies = [
    "gptdb[client,cli]",
    "gptdb_ext",
    "shortuuid",
    # 2.0.29 not support duckdb now
    "SQLAlchemy>=2.0.25, <2.0.29",
    # for cache
    "msgpack",
    # for AWEL operator serialization
    "cloudpickle",
]

[project.urls]
Homepage = "https://github.com/khulnasoft/GPT-DB"
Documentation = "http://docs.gptdb.cn/docs/overview"
Repository = "https://github.com/khulnasoft/GPT-DB.git"
Issues = "https://github.com/khulnasoft/GPT-DB/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
managed = true
dev-dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/gptdb_client"]
exclude = [
    "src/gptdb_client/**/tests",
    "src/gptdb_client/**/tests/*",
    "src/gptdb_client/tests",
    "src/gptdb_client/tests/*",
    "src/gptdb_client/**/examples",
    "src/gptdb_client/**/examples/*"
]